apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  superuser: 'admin'
  spassword: 'Saturday_123'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-deployment
spec:
  selector:
    matchLabels:
      app: sso
  replicas: 1
  template:
    metadata:
      labels:
        app: sso
    spec:
      containers:
      - name: pythonwebfsd
    # enter the path to your image, be sure to include the correct region prefix    
        image: sjc.ocir.io/oraclepartnersas/sso-flask:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: pythonwebsecret
---
apiVersion: v1
kind: Service
metadata:
  name: sso-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sso

---
